import fs from 'node:fs'
import path from 'node:path'
import { isDocsMintCollectionKind } from '../registry/collection-kinds.js'
import { isDocsMintDocForm } from '../registry/doc-forms.js'
import { isDocsCollectionKey } from '../registry/legacy.js'
import type { DocsMintConfig } from '../schema/index.js'

const COLLECTION_MODES_BY_KIND = {
  content: ['collection-index', 'collection-entry', 'version-root'],
  writing: ['collection-index', 'collection-entry'],
  page: ['collection-index', 'collection-entry'],
} as const

export interface PluginManifest {
  viewDescriptors: Array<{
    viewKey: string
    requiresRenderedEntry: boolean
    shell: boolean
  }>
  shellLayoutByPrefix: Record<string, 'docs' | 'writing' | 'page'>
  presentationModules: Record<string, string>
  astroViewImports: Record<string, string>
  docFormKeys: string[]
}

export interface CollectPluginManifestOptions {
  /** Docs project root — when set, only existing Astro view files are registered. */
  projectRoot?: string
}

function astroViewFileExists(projectRoot: string | undefined, relativePath: string): boolean {
  if (!projectRoot) {
    return true
  }
  const absolute = path.resolve(projectRoot, relativePath.replace(/^\.\//, ''))
  return fs.existsSync(absolute)
}

function registerAstroViewImport(
  astroViewImports: Record<string, string>,
  projectRoot: string | undefined,
  viewKey: string,
  viewsDir: string,
  mode: string,
): void {
  const joined = path.posix.join(viewsDir.replace(/\/$/, ''), `${mode}.astro`)
  const astroPath = joined.startsWith('./') ? joined : `./${joined}`
  if (!astroViewFileExists(projectRoot, astroPath)) {
    return
  }
  astroViewImports[viewKey] = astroPath
}

/** @param site Config after `withDefaults()`. */
export function collectPluginManifest(
  site: DocsMintConfig,
  options: CollectPluginManifestOptions = {},
): PluginManifest {
  const { projectRoot } = options
  const collections = site.collections ?? {}
  const viewDescriptors: PluginManifest['viewDescriptors'] = []
  const shellLayoutByPrefix: PluginManifest['shellLayoutByPrefix'] = {}
  const presentationModules: Record<string, string> = {}
  const astroViewImports: Record<string, string> = {}
  const docFormKeys: string[] = []

  for (const [collectionKey, collection] of Object.entries(collections)) {
    if (!collection?.enabled || isDocsCollectionKey(collectionKey)) {
      continue
    }
    const render = collection.render
    if (!render?.presentation && !render?.views) {
      continue
    }
    const kind = collection.kind
    const modes =
      kind && isDocsMintCollectionKind(kind)
        ? [...COLLECTION_MODES_BY_KIND[kind]]
        : [...COLLECTION_MODES_BY_KIND.content]
    const shellLayout = kind === 'writing' ? 'writing' : kind === 'page' ? 'page' : 'docs'
    shellLayoutByPrefix[collectionKey] = shellLayout

    for (const mode of modes) {
      viewDescriptors.push({
        viewKey: `${collectionKey}:${mode}`,
        requiresRenderedEntry:
          mode === 'collection-entry' ||
          mode === 'version-root' ||
          (mode === 'collection-index' && shellLayout === 'docs'),
        shell: true,
      })
    }

    if (render.presentation) {
      presentationModules[collectionKey] = render.presentation
    }
    if (render.views) {
      for (const mode of modes) {
        registerAstroViewImport(astroViewImports, projectRoot, `${collectionKey}:${mode}`, render.views, mode)
      }
    }
  }

  const docForms = site.extensions?.docForms ?? {}
  for (const [formKey, descriptor] of Object.entries(docForms)) {
    if (isDocsMintDocForm(formKey)) {
      continue
    }
    docFormKeys.push(formKey)
    const formPrefix = `form-${formKey}`
    shellLayoutByPrefix[formPrefix] = 'docs'
    for (const mode of ['collection-index', 'collection-entry', 'version-root'] as const) {
      viewDescriptors.push({
        viewKey: `${formPrefix}:${mode}`,
        requiresRenderedEntry: true,
        shell: true,
      })
      if (descriptor.views) {
        registerAstroViewImport(astroViewImports, projectRoot, `${formPrefix}:${mode}`, descriptor.views, mode)
      }
    }
    if (descriptor.presentation) {
      presentationModules[`form:${formKey}`] = descriptor.presentation
    }
  }

  return {
    viewDescriptors,
    shellLayoutByPrefix,
    presentationModules,
    astroViewImports,
    docFormKeys,
  }
}

export function formatPluginManifestModule(manifest: PluginManifest): string {
  return `// Generated by docsmint — do not edit.
export const PLUGIN_ROUTE_VIEW_DESCRIPTORS = ${JSON.stringify(manifest.viewDescriptors, null, 2)}

export const PLUGIN_SHELL_LAYOUT_BY_PREFIX = ${JSON.stringify(manifest.shellLayoutByPrefix, null, 2)}

export const PLUGIN_PRESENTATION_MODULES = ${JSON.stringify(manifest.presentationModules, null, 2)}

export const PLUGIN_ASTRO_VIEW_IMPORTS = ${JSON.stringify(manifest.astroViewImports, null, 2)}

export const PLUGIN_DOC_FORM_KEYS = ${JSON.stringify(manifest.docFormKeys, null, 2)}
`
}

export function collectPluginPathsToMount(manifest: PluginManifest): Set<string> {
  const pathsToMount = new Set<string>()
  for (const relativePath of [
    ...Object.values(manifest.presentationModules),
    ...Object.values(manifest.astroViewImports),
  ]) {
    const normalized = relativePath.replace(/^\.\//, '')
    const top = normalized.split('/')[0]
    if (top) {
      pathsToMount.add(top)
    }
  }
  return pathsToMount
}
